### ISSUE TITLE
Example of using saxerator writing a file.

### ISSUE THREAD

**Issue by mgurley** [soulcutter/saxerator#21]
The following Stackoverflow question indicates that the saxerator gem can be used to generate a XML file as a stream:
https://stackoverflow.com/questions/21748227/how-to-stream-large-xml-in-rails-3-2

Is there an example of how to achieve this?

I would like to stream a large XML file as it is dynamically built.

**Comment by soulcutter** [comment]
I'm going to close this. I still don't know quite what this feature would look like, but unless there's a specific proposal to discuss I don't think this will go anywhere.

I lean towards this being out-of-scope for this gem, which is primarily an XML stream consumer.
