### ISSUE TITLE
Replace nil-like bits of EmptyElement class

### ISSUE THREAD

**Issue by soulcutter** [soulcutter/saxerator#26]
I'm honestly not sure quite what I was thinking with the way `EmptyElement` works. Seems a mistake in retrospect, though I haven't yet given thought to its replacement.

**Comment by fanantoxa** [comment]
@soulcutter Didn't get the idea. Would you explain a bit more? I'll try to find a solution for that

**Comment by soulcutter** [comment]
I want to remove `#nil?` and `#!` - it doesn't make sense to me, and is not idiomatic.
