### ISSUE TITLE
How to ignore encoding error?

### ISSUE THREAD

**Issue by ZuevEvgenii** [soulcutter/saxerator#32]
For example I have such error: 

`error on line 1890 at column 14: Encoding error`

It is undefined symbol.

How can I replace it to blank, ignore it or go to next tag?

**Comment by soulcutter** [comment]
Can you give the stack trace?

**Comment by soulcutter** [comment]
Closing without resolution - I suspect it's an issue at the nokogiri level, but am not sure how to reproduce this.
