### ISSUE TITLE
Rubocop config

### ISSUE THREAD

**Issue by fanantoxa** [soulcutter/saxerator#36]
@soulcutter Do you use Rubocop?
Maybe we can create config file and CI integration for that to be on the same code style?

**Comment by soulcutter** [comment]
I am open to using it, although my preference is for fairly loose rules (not a big fan of the default ones)

**Comment by fanantoxa** [comment]
@soulcutter Ok. I'll create useful config for rubocop for this and maybe update code to have same style on all files at the weekend.

**Comment by soulcutter** [comment]
Thanks!

**Comment by fanantoxa** [comment]
@soulcutter Updated PR: https://github.com/soulcutter/saxerator/pull/40

**Comment by fanantoxa** [comment]
Already in master
