### ISSUE TITLE
Update XmlBuilder to use REXML class

### ISSUE THREAD

**Issue by fanantoxa** [soulcutter/saxerator#43]
We need to have single type of object for all parsers when out_type is xml.
So We need to update the code to return REXML intead of nokogiry:xml and update code to use it for ox parser too.
(REXML)[http://ruby-doc.org/stdlib-2.2.3/libdoc/rexml/rdoc/REXML/Document.html]

**Comment by fanantoxa** [comment]
@soulcutter Is task: [Implement REXML support](https://github.com/soulcutter/saxerator/issues/3) the same?

**Comment by soulcutter** [comment]
No, the REXML support is to write an adapter. This is to use REXML as the xml output type

Bradley Schaefer

**Comment by fanantoxa** [comment]
@soulcutter ok. Than just take a look on PR: https://github.com/soulcutter/saxerator/pull/46

**Comment by soulcutter** [comment]
Closed via c865cf9
