### ISSUE TITLE
dependencies fails

### ISSUE THREAD

**Issue by fanantoxa** [soulcutter/saxerator#48]
@soulcutter  Since we have nokogiri and ox only as dev deps: 
```
s.add_development_dependency 'nokogiri', '>= 1.4.0'
s.add_development_dependency 'ox'
```
So we have to make and not only dev or add `Attention` warning on `Readme.md` that we have to manually add one of them (or both) in project.

**Comment by soulcutter** [comment]
We should note in the README that to use the `:ox` or `:nokogiri` adapters you must provide them on the load path.

**Comment by fanantoxa** [comment]
@soulcutter Got it.
