### ISSUE TITLE
Release new version. 

### ISSUE THREAD

**Issue by fanantoxa** [soulcutter/saxerator#51]
@soulcutter I think we're ready to release new version. 
I've also Update Doc a bit with new updates. 
So since gem became self-sufficient, have and same output for different adapters, all bugs that we know fixed and we have huge breaking changes maybe we can finally release major version like `1.0.0` :birthday:?

What do you think about it?

**Comment by fanantoxa** [comment]
@soulcutter Please let me know when you'll be ready for this))

**Comment by fanantoxa** [comment]
@soulcutter  T__T

**Comment by soulcutter** [comment]
Released 0.9.8

I think the 1.0 milestone should occur after fixing #26
