### ISSUE TITLE
How can I get a count of  ?

### ISSUE THREAD

**Issue by Serhii-Danovsky** [soulcutter/saxerator#64]
parser = Saxerator.parser(File.new(file))
    parser.for_tag('RECORD').each_with_index do |item, index|
    end
How can I get a count of all  parser.for_tag('RECORD') elements?

**Comment by fanantoxa** [comment]
@Serhii-Danovsky Hi, sorry for late response.
```
Saxerator.parser(file).for_tag(:artist).count
```
Works.

Actually this is gem for SAX parsing, so your xml became a Stream of parsed nodes. It was made to allow not to load all xml file at once in memory.
